org: jabba01
app: lifi-fee-collection-reporting
service: events-scraper

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3003
    lambdaPort: 3005

functions:
  scrapFeeCollectorEvents:
    handler: dist/main.scrapFeeCollectorEvents
    description: Scrap the fee collected events of a LI.FI FeeCollector contract on a given chain
    memorySize: 512
    timeout: 30
    environment:
      NODE_ENV: dev
      LOG_LEVEL: info
      MONGODB_PROTOCOL: mongodb
      MONGODB_HOST: localhost
      MONGODB_PORT: 27017
      MONGODB_DEFAULT_DATABASE: lfcr
    events:
      - http: 
          path: feecollected-scraping/{chainKey}
          method: GET
          request:
            parameters:
              paths:
                chainKey: true

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs20.x
  stage: dev
