import { Env } from 'hono'
import { describeRoute } from 'hono-openapi'
import { resolver, validator } from 'hono-openapi/zod'
import { Factory } from 'hono/factory'
import { z } from 'zod'
import { AddressSchemaSpec, Int256, ITag } from '../common'
import { reportFeesCollectedByIntegrator } from '@jabba01/lfcr-fees-reporter'
import { logger as wLogger } from '@jabba01/lfcr-common/dist/logger'

const logger = wLogger.child({
  label: 'getFeesCollectedByIntegrator',
})

export function getFeesCollectedByIntegrator<E extends Env, TTag extends ITag>(
  factory: Factory<E>,
  tag: TTag
) {
  return factory.createHandlers(
    describeRoute({
      summary: 'Get Fees Collected by Integrator',
      description:
        'Returns the LI.FI fee collection events associated to a specific integrator.\n\Corresponding onchain log events are generated by the LI.FI FeeCollector contract deployed on chains',
      tags: [tag.tag],
      responses: {
        200: {
          description: 'Fees collected by the integrator',
          content: {
            'application/json': {
              schema: resolver(
                z.object({
                  address: AddressSchemaSpec,
                  balance: Int256.openapi({
                    description: 'Amount of tokens in WEI',
                  }),
                })
              ),
            },
          },
        },
      },
    }),
    validator(
      'query',
      z.object({
        integratorId: AddressSchemaSpec,
      })
    ),
    async (c) => {
      const { integratorId } = c.req.valid('query')
      const report = await reportFeesCollectedByIntegrator(integratorId as string)

      return c.json(report.toString(),
        200
      )
    }
  )
}
