import { reportFeesCollectedByIntegrator } from '@jabba01/lfcr-fees-reporter'
import { Env } from 'hono'
import { describeRoute } from 'hono-openapi'
import { resolver, validator } from 'hono-openapi/zod'
import { Factory } from 'hono/factory'
import { Address } from 'viem'
import { z } from 'zod'
import { AddressSchemaSpec, Int256, ITag } from '../common'

export function getFeesCollectedByIntegrator<E extends Env, TTag extends ITag>(
  factory: Factory<E>,
  tag: TTag
) {
  return factory.createHandlers(
    describeRoute({
      summary: 'Get Fees Collected by Integrator',
      description:
        'Returns the LI.FI fee collection events associated to a specific integrator.\n\nCorresponding onchain log events are generated by the LI.FI FeeCollector contract deployed on chains',
      tags: [tag.tag],
      responses: {
        200: {
          description:
            'Retrieve a sum-up report of all token fees collected by an integrator on chains, as well as corresponding LI.FI protocol share.',
          content: {
            'application/json': {
              schema: resolver(
                z
                  .object({
                    integrator: z.string().openapi({
                      description: 'Onchain account address of the integrator',
                    }),
                    feesCollected: z
                      .array(
                        z
                          .object({
                            chainKey: z.string().openapi({
                              description:
                                'Chain key where the FeeCollector contract is deployed',
                            }),
                            token: z.string().openapi({
                              description: 'Token address of the collected fees',
                            }),
                            totalIntegrator: Int256.openapi({
                              description:
                                'Total amount of tokens collected as fees by the integrator, a big number expressed in string format',
                            }),
                            totalLifi: Int256.openapi({
                              description:
                                'Total amount of tokens collected as fees by the LI.FI protocol, a big number expressed in string format',
                            }),
                          })
                          .openapi({
                            description:
                              'Total amounts of the chain-specific token collected as fees by the integrator and the LI.FI protocol.',
                          })
                      )
                      .openapi({
                        description:
                          'List of the collected fees, grouped by chain tokens',
                      }),
                  })
                  .openapi({
                    description: 'Report of total fees collected by the integrator',
                  })
              ),
            },
          },
        },
      },
    }),
    validator(
      'param',
      z.object({
        integrator: AddressSchemaSpec,
      })
    ),
    async (c) => {
      const { integrator } = c.req.valid('param')
      const report = await reportFeesCollectedByIntegrator(<Address>integrator)
      return c.json(report, 200)
    }
  )
}
