import { Env } from 'hono'
import { describeRoute } from 'hono-openapi'
import { resolver, validator } from 'hono-openapi/zod'
import { Factory } from 'hono/factory'
import { z } from 'zod'
import { AddressSchemaSpec, ITag } from '../common'
import { getFeeCollectionEventsByIntegrator } from '@jabba01/lfcr-fees-reporter'

export function getFeesCollectedEventsByIntegrator<E extends Env, TTag extends ITag>(
  factory: Factory<E>,
  tag: TTag
) {
  return factory.createHandlers(
    describeRoute({
      summary: 'Get FeeCollected Events by Integrator',
      description:
        'Returns the onchain LI.FI fee collection events associated to a specific integrator.\n\nCorresponding onchain log events are generated by the LI.FI FeeCollector contract deployed on chains',
      tags: [tag.tag],
      responses: {
        200: {
          description:
            'Retrieve a paginated list of all onchain fee collection event related to a given integrator.',
          content: {
            'application/json': {
              schema: resolver(
                z
                  .object({
                    chainKey: z.string().openapi({
                      description: 'Chain where the fees were collected',
                    }),
                    txHash: z.string().openapi({
                      description: 'Transaction hash of the fee collection event',
                    }),
                    blockTag: z.string().openapi({
                      description: 'Block tag where the fee collection event was emitted',
                    }),
                    token: z.string().openapi({
                      description: 'Token address of the collected fee',
                    }),
                    integrator: z.string().openapi({
                      description: 'Account address/id of the integrator',
                    }),
                    integratorFee: z.string().openapi({
                      description:
                        'Amount of fees collected by the integrator, expressed in the token unit',
                    }),
                    lifiFee: z.string().openapi({
                      description:
                        'Amount of fees collected by the LI.FI protocol, expressed in the token unit',
                    }),
                    docId: z.string().optional().openapi({
                      description: 'Database document identifier of the event',
                    }),
                  })
                  .openapi({
                    description: 'List of fees collected on chain by the integrator',
                  })
              ),
            },
          },
        },
      },
    }),
    validator(
      'param',
      z
        .object({
          integrator: AddressSchemaSpec,
        })
        .required()
        .openapi({
          description: 'Onchain account address of the integrator',
        })
    ),
    validator(
      'query',
      z.object({
        limit: z.string().optional().openapi({
          description: 'Maximum number of events to return, default size is 20',
        }),
        page: z.string().optional().openapi({
          description: 'Index of the event result page to start from, considering the set limit, default is 0',
        }),
      })
    ),
    async (c) => {
      const { integrator } = c.req.valid('param')
      const { limit, page } = c.req.valid('query')
      const report = await getFeeCollectionEventsByIntegrator(
        <string>integrator,
        parseInt(limit) ?? 20,
        parseInt(page) ?? 0
      )
      return c.json(report, 200)
    }
  )
}
