import { logger as wLogger } from '@jabba01/lfcr-common/dist/logger'
import { startScraping } from '@jabba01/lfcr-events-scraper'
import { ChainKey } from '@lifi/types'
import { Env } from 'hono'
import { describeRoute } from 'hono-openapi'
import { resolver, validator } from 'hono-openapi/zod'
import { Factory } from 'hono/factory'
import { z } from 'zod'
import { AddressSchemaSpec, ChainKeySchemaSpec, Int256, ITag } from '../common'

const logger = wLogger.child({
  label: 'postScrapFeesCollectedOnChain',
})

export function postScrapFeesCollectedOnChain<E extends Env, TTag extends ITag>(
  factory: Factory<E>,
  tag: TTag
) {
  return factory.createHandlers(
    describeRoute({
      summary: 'Scrap Fees Collected on Chain',
      description:
        'Initiate a scan session of LI.FI fee collection events on a given chain.\n\n' +
        'Corresponding onchain log events are generated by the LI.FI FeeCollector contract ' +
        'deployed on chains, spotted and stored in a database for later reporting.\n\n' +
        'The scraping session is resumed from last scanned block, in batches. Depending on ' +
        'last scraping session time, many blocks might have to be scanned, ' +
        'leading to a potentially long response time.',
      tags: [tag.tag],
      responses: {
        200: {
          description: 'Sum-up info of the events scraping session.',
          content: {
            'application/json': {
              schema: resolver(
                z.object({
                  blocksScanned: z.number().openapi({
                    description: 'Number of blocks scanned'
                  }),
                  eventsNew: z.number().openapi({
                    description: 'Number of new onchain events collected'
                  }),
                  message: z.string().openapi({
                    description: 'Textual sum-up of the scraping session'
                  }),
                }).openapi({
                  description: 'Result of an events scraping session'
                })
              ),
            },
          },
        },
      },
    }),
    validator(
      'param',
      z.object({
        chain: ChainKeySchemaSpec,
      })
    ),
    async (c) => {
      const { chain } = c.req.valid('param')
      const report = await startScraping(<ChainKey>chain)
      return c.json(report, 201)
    }
  )
}
