import { ChainKey } from '@lifi/types'
import { Env } from 'hono'
import { describeRoute } from 'hono-openapi'
import { validator } from 'hono-openapi/zod'
import { Factory } from 'hono/factory'
import { z } from 'zod'
import { ChainKeySchemaSpec, ITag } from '../common'
import { spawnEventScrapingProcess } from '../events-scraping/events-scraping-spawner'
import { EventScrapingSessionInitResultSchemaSpec } from '../events-scraping/events-scraping-zod.schema'

export function postScrapFeesCollectedOnChain<E extends Env, TTag extends ITag>(
  factory: Factory<E>,
  tag: TTag
) {
  return factory.createHandlers(
    describeRoute({
      summary: 'Scrap Fees Collected on Chain',
      description:
        'Initiate a scanning & extraction session of LI.FI fee collection events on a given chain.\n\n' +
        'Corresponding onchain log events are generated by the LI.FI FeeCollector contract ' +
        'deployed on chains, spotted and stored in a database for later reporting.\n\n' +
        'The scraping session is resumed from last scanned block, in batches. Depending on ' +
        'last scraping session time, many blocks might have to be scanned.',
      tags: [tag.tag],
      responses: {
        200: {
          description: 'Result of the events scraping session initiation.',
          content: {
            'application/json': {
              schema: EventScrapingSessionInitResultSchemaSpec
            },
          },
        },
      },
    }),
    validator(
      'param',
      z.object({
        chain: ChainKeySchemaSpec,
      })
    ),
    async (c) => {
      const { chain } = c.req.valid('param')
      //const report = await startScraping(<ChainKey>chain) // ScrapingSessionResultSchemaSpec
      const report = spawnEventScrapingProcess(<ChainKey>chain) // EventScrapingSessionInitResultSchemaSpec
      return c.json(report, 201)
    }
  )
}
